[sources.my_source_id]
type = "file"
ignore_older_secs = 600
include = [ "/var/log/nginx/access.log" ]
read_from = "beginning"

[sinks.my_sink_id]
type = "kafka"
inputs = [ "my_source_id" ]
bootstrap_servers = "xxxxxxxxxx"
key_field = "nginx"
topic = "nginx-logs"
compression = "none"

[sinks.my_sink_id.encoding]
codec = "avro"

[sinks.my_sink_id.encoding.avro]
schema = '''
{
    "type": "record",
    "name": "log",
    "fields": [
        {"name": "ip", "type": "string"},
        {"name": "remote_user", "type": "string"},
        {"name": "time_local", "type": "string"},
        {"name": "request", "type": "string"},
        {"name": "status", "type": "int"},
        {"name": "bytes_sent", "type": "int"},
        {"name": "http_referrer", "type": "string"},
        {"name": "agent", "type": "string"}
    ]
}
'''
